[build]
command = ""
publish = "apps/frontend"

[functions]
node_bundler = "esbuild"

[[scheduled.functions]]
path = "functions/metrics.ts"
schedule = "@hourly"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
